FROM node:lts-bookworm

RUN apt-get update && \
  apt-get install -y --no-install-recommends chromium ca-certificates && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /bot
COPY ./bot/package*.json ./
RUN npm ci
COPY ./bot/bot.mjs ./bot.mjs

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
RUN chown -R node:node /bot
USER node
CMD ["node", "bot.mjs"]
